// Generated by https://quicktype.io

// export interface ItunesTypes {
//   resultCount?: number;
//   results?: Result[];
// }


export interface Film {
  kinopoiskId:                number;
  imdbId:                     string;
  nameRu:                     string;
  nameEn:                     null;
  nameOriginal:               string;
  posterUrl:                  string;
  posterUrlPreview:           string;
  coverUrl:                   string;
  logoUrl:                    string;
  reviewsCount:               number;
  ratingGoodReview:           number;
  ratingGoodReviewVoteCount:  number;
  ratingKinopoisk:            number;
  ratingKinopoiskVoteCount:   number;
  ratingImdb:                 number;
  ratingImdbVoteCount:        number;
  ratingFilmCritics:          number;
  ratingFilmCriticsVoteCount: number;
  ratingAwait:                number;
  ratingAwaitCount:           number;
  ratingRfCritics:            number;
  ratingRfCriticsVoteCount:   number;
  webUrl:                     string;
  year:                       number;
  filmLength:                 number;
  slogan:                     string;
  description:                string;
  shortDescription:           string;
  editorAnnotation:           string;
  isTicketsAvailable:         boolean;
  productionStatus:           null;
  type:                       string;
  ratingMpaa:                 string;
  ratingAgeLimits:            string;
  countries:                  Country[];
  genres:                     Genre[];
  startYear:                  null;
  endYear:                    null;
  serial:                     boolean;
  shortFilm:                  boolean;
  completed:                  boolean;
  hasImax:                    boolean;
  has3D:                      boolean;
  lastSync:                   string;
}

export interface Country {
  country: string;
}

export interface Genre {
  genre: string;
}
